### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by glennq14**
Please check for enhancements.

### CODE REVIEW

**Comment by glennq14** [comment]
More enhancement for ipad please merge

**Review by cherbear263 — CHANGES_REQUESTED** [review]
Hi Glenn, thanks for fixing the navbar in mobile. 
There is a problem with the image at a breakpoint of about 990px (see image). Could you fix that please? 
image

I have used tailwindCSS for this - so here is a link to the docs so that you can see what breakpoints have been used 
https://tailwindcss.com/docs/screens

**Comment by glennq14** [comment]
I adjusted the max width

**Review by cherbear263 — COMMENTED** [review]
Looks good. Thanks, Glenn.

**Pull request merged**
